### ISSUE TITLE
Adding recipes & metric units: 1 + 0.5 = 10.5

### ISSUE THREAD

**Issue by dolodobendan** [nikhil-31/Mixology#3]
When adding a recipe and using metric units, the selection of "Amount & Unit" doesn't work correctly. For example, if I select "1" on the left, "0.5" in the middle and "-", I'd expect to get 1.5. Instead, I get 10.5.

**Comment by nikhil-31** [comment]
I don't manage the backend. I just built the client app as a project from 3 years ago. I think a good place to ask this question is in the link below. The app is no longer being maintained either.

https://forum.kodi.tv/showthread.php?tid=235298
